### ISSUE TITLE
Add andi to DI frameworks

### ISSUE THREAD

**Issue by vu3jej** [sfermigier/awesome-dependency-injection-in-python#14]
This isn't a well known library, but is used with https://github.com/scrapinghub/web-poet and other Zyte projects.

https://github.com/scrapinghub/andi

**Comment by sfermigier** [comment]
Thanks. Added in https://github.com/sfermigier/awesome-dependency-injection-in-python/commit/5cbc33cd45c1d87d877a31e696419a6b24c7ec41
